### PR TITLE
Archive improvements

### LINKED ISSUE #59: Adjust Archive Workflow
There should be a setup job that creates the release tag and subsequent jobs should use that tag instead of searching for it (and maybe creating it) in every job. 
Might be worth to play around with the gh cli here as many jobs fail in n the pb_releases or in the pb_upload lines.

### PR DESCRIPTION
**Pull request by mrcaseb**
closes #59 

- passes archive tag to archive job (release tag creation was already done anyways!)
- reads archive tag from env var and passes it to archive function

### CODE REVIEW

**Review by tanho63 — APPROVED** [review]

File: R/archive.R [hunk 1]
```diff
@@ -18,7 +18,7 @@ nflverse_archive <- function(release_name, archive_tag){
   )
 
   # cli::cli_alert_info("Uploading Files to {.path nflverse/nflverse-data-archives@{archive_tag}}")
-  gh_cli_release_upload <- function(
```
Comment (tanho63) [inline R/archive.R]: yike
